const state = {
    articles: [],
    isInitialLoadComplete: false,
    isDataFullyLoaded: false, // New flag for split mode readiness
    isHydrated: false,
    hydrationPromise: null,
    deletedRecords: [],
    activeArticleId: null,
    activeReaderTheme: 'default',
    currentMode: 'read',
    isFullscreen: false,
    directoryHandle: null,
    currentBulletIndex: 0,
    lastClickTime: 0,
    chartInstances: {},
    studySession: { isActive: false, isQuizMode: false, cards: [], currentIndex: 0, isRating: false },
    settings: {},
    activeLibraryCategory: 'All',
    libraryRender: {
        isRendering: false,
        currentIndex: 0,
        filteredArticles: [],
        searchTimeout: null,
        lastSavedHash: '', // OPTIMIZATION: Track last saved hash to prevent redundant saves
    },
    flashcardRender: {
        searchResults: [],
        selectedIndex: -1
    },
    selectedImageContainer: null,
    savedRange: null,
    pwa: { installPromptEvent: null },
    dropboxToken: null,
    dropboxUser: null,
    isDropboxReady: false,
    isSyncing: false,
    isSaving: false,
    _savePromise: null,
    isArticleDirty: false,
    isPristineNewArticle: false,
    lastHeartKeyPressTime: 0,
    focusSession: {
        isActive: false,
        articles: [],
        currentIndex: 0,
        isStageMode: false,
        currentSlideIndex: 0,
        scrollStops: [],
        isCinematicActive: false,
        teleprompterActive: false,
        teleprompterSize: 30,
        teleprompterFontSize: 1.1,
    },
    autosaveInterval: null,
    // New states from ProtoTags
    tags: {},
    visualMapState: { snapshots: [], stickyNotes: {} },
    mindMapState: { snapshots: [] },
    dataCache: { isBuilt: false, mindMapSnippets: {} },
    scrollToTagId: null,
    suggestionTimeout: null,
};

export default state;
