# Netlify configuration file

[build]
  publish = "."
  functions = "netlify/functions"

# Rule 1: Proxy for cached/prefixed model requests (THE NEW FIX)
# This rule handles requests that the library makes using a /models/ prefix.
[[redirects]]
  from = "/models/Xenova/*"
  to = "https://huggingface.co/Xenova/:splat"
  status = 200
  force = true

# Rule 2: Proxy for direct model requests (The original rule)
# This handles the initial configuration file requests.
[[redirects]]
  from = "/Xenova/*"
  to = "https://huggingface.co/Xenova/:splat"
  status = 200
  force = true

# Rule 3: Standard Single Page Application (SPA) fallback (MUST BE LAST)
# This is the "catch-all" rule for your app's routing.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
